django_coinpayments/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views

app_name = 'django_coinpayments'
urlpatterns = [

]

example/example/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from .views import PaymentSetupView, PaymentList, create_new_payment, PaymentDetail

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('django_coinpayments.urls', namespace='django_coinpayments')),
    url(r'^$', PaymentSetupView.as_view(), name='payment_setup'),
    url(r'^payments/$', PaymentList.as_view(), name='payment_list'),
    url(r'^payment/(?P<pk>[0-9a-f-]+)$', PaymentDetail.as_view(), name='payment_detail'),
    url(r'^payment/new/(?P<pk>[0-9a-f-]+)$', create_new_payment, name='payment_new'),
]

django_coinpayments/models.py
# -*- coding: utf-8 -*-

from django.db import models

from model_utils.models import TimeStampedModel
import uuid
from django.utils import timezone
from .coinpayments import CoinPayments
from .exceptions import CoinPaymentsProviderError
from .utils import get_coins_list
import datetime
from decimal import Decimal
from django.utils.translation import ugettext_lazy as _


class CoinPaymentsTransaction(TimeStampedModel):
    id = models.CharField(max_length=100, verbose_name=_('id'), primary_key=True, editable=True)
    address = models.CharField(max_length=150, verbose_name=_('Address'))
    amount = models.DecimalField(max_digits=65, decimal_places=18, verbose_name=_('Amount'))
    confirms_needed = models.PositiveSmallIntegerField(verbose_name=_('Confirms needed'))
    qrcode_url = models.URLField(verbose_name=_('QR Code Url'))
    status_url = models.URLField(verbose_name=_('Status Url'))
    timeout = models.DateTimeField(verbose_name=_('Valid until'))

    def __str__(self):
        return self.id

    class Meta:
        verbose_name = _('CoinPayments Transaction')
        verbose_name_plural = _('CoinPayments Transactions')


class PaymentManager(models.Manager):
    def get_late_payments(self):
        """
        Returns payments that are already late by timeout, not filtering their status
        """
        return self.get_queryset().filter(provider_tx__isnull=False,
                                          provider_tx__timeout__lte=timezone.now())

    def get_cancelled_payments(self):
        """
        Returns payments that are already late and should be timed out
        """
        return self.get_late_payments().filter(status__in=[self.model.PAYMENT_STATUS_PENDING])

    def get_timed_out_payments(self):
        """
        Returns payments that are timed out
        """
        return self.get_late_payments().filter(status__in=[self.model.PAYMENT_STATUS_TIMEOUT])

    def mark_timed_out_payments(self):
        """
        Marks late payments as timed out
        """
        return self.get_late_payments().update(status=self.model.PAYMENT_STATUS_TIMEOUT)

    def get_pending_payments(self):
        return self.get_queryset() \
            .filter(status__in=[self.model.PAYMENT_STATUS_PENDING]) \
            .exclude(id__in=self.get_late_payments())

    def get_successful_payments(self):
        """
        Returns successfully paid payments
        """
        return self.get_queryset().filter(status__in=[self.model.PAYMENT_STATUS_PAID])


class Payment(TimeStampedModel):
    PAYMENT_STATUS_PAID = 'PAID'
    PAYMENT_STATUS_TIMEOUT = 'TOUT'
    PAYMENT_STATUS_PENDING = 'PEND'
    PAYMENT_STATUS_PROVIDER_PENDING = 'PRPE'
    PAYMENT_STATUS_CANCELLED = 'CNCL'
    PAYMENT_STATUS_CHOICES = (
        (PAYMENT_STATUS_PROVIDER_PENDING, _('Provider-related payment pending')),
        (PAYMENT_STATUS_PENDING, _('Pending')),
        (PAYMENT_STATUS_CANCELLED, _('Cancelled')),
        (PAYMENT_STATUS_TIMEOUT, _('Timed out')),
        (PAYMENT_STATUS_PAID, _('Paid'))
    )
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    currency_original = models.CharField(max_length=8, choices=get_coins_list(), verbose_name=_('Original currency'))
    currency_paid = models.CharField(max_length=8, choices=get_coins_list(), verbose_name=_('Payment currency'))
    amount = models.DecimalField(max_digits=65, decimal_places=18, verbose_name=_('Amount'))
    amount_paid = models.DecimalField(max_digits=65, decimal_places=18, verbose_name=_('Amount paid'))
    buyer_email = models.EmailField(max_length=254, null=True, blank=True, verbose_name=_('Buyer email'))
    provider_tx = models.OneToOneField(CoinPaymentsTransaction, on_delete=models.CASCADE,
                                       verbose_name=_('Payment transaction'), null=True, blank=True)
    status = models.CharField(max_length=4, choices=PAYMENT_STATUS_CHOICES)
    objects = PaymentManager()

    class Meta:
        verbose_name = _('Payment')
        verbose_name_plural = _('Payments')

    def __str__(self):
        return "{} of {} - {}".format(str(self.amount_paid.normalize()), str(self.amount.normalize()), self.get_status_display())

    def is_paid(self):
        return self.status == self.PAYMENT_STATUS_PAID

    def amount_left(self):
        return self.amount - self.amount_paid

    def is_cancelled(self):
        if self.provider_tx:
            return self.provider_tx.timeout < timezone.now()

    def create_tx(self, invoice=None, **kwargs):
        """
        :param invoice: Field for custom use. Default - payment id
        :param kwargs:
            address      The address to send the funds to in currency_paid network
            buyer_email  Optionally (but highly recommended) set the buyer's email address.
                         This will let us send them a notice if they underpay or need a refund.
            buyer_name   Optionally set the buyer's name for your reference.
            item_name    Item name for your reference,
                         will be on the payment information page and in the IPNs for the transaction.
            item_number  Item number for your reference,
                         will be on the payment information page and in the IPNs for the transaction.
            custom       Field for custom use.
            ipn_url      URL for your IPN callbacks.
                         If not set it will use the IPN URL in your Edit Settings page if you have one set.
        :return: `CoinPaymentsTransaction` instance
        """
        obj = CoinPayments.get_instance()
        if not invoice:
            invoice = self.id
        params = dict(amount=self.amount_left(), currency1=self.currency_original,
                      currency2=self.currency_paid, buyer_email=self.buyer_email, invoice=invoice)
        params.update(**kwargs)
        result = obj.create_transaction(params)
        if result['error'] == 'ok':
            result = result['result']
            timeout = timezone.now() + datetime.timedelta(seconds=result['timeout'])
            c = CoinPaymentsTransaction.objects.create(id=result['txn_id'],
                                                       amount=Decimal(result['amount']),
                                                       address=result['address'],
                                                       confirms_needed=int(result['confirms_needed']),
                                                       qrcode_url=result['qrcode_url'],
                                                       status_url=result['status_url'],
                                                       timeout=timeout)
            self.provider_tx = c
            self.save()
        else:
            raise CoinPaymentsProviderError(result['error'])

        return c

django_coinpayments/forms.py
from django import forms
from .utils import get_coins_list


class ChooseCoinToPayForm(forms.Form):
    currency = forms.ChoiceField(choices=get_coins_list(),
                                 widget=forms.RadioSelect(),
                                 label='',
                                 required=True)

django_coinpayments/views.py
# -*- coding: utf-8 -*-
from django.views.generic import (
    CreateView,
    DeleteView,
    DetailView,
    UpdateView,
    ListView
)

from .models import (
    CoinPaymentsTransaction,
    Payment,
)

from django.views.decorators.csrf import csrf_exempt
from django.http.response import HttpResponseBadRequest
from django.conf import settings
from .utils import create_ipn_hmac
from decimal import Decimal
import logging

logger = logging.getLogger(__name__)


class CoinPaymentsTransactionCreateView(CreateView):
    model = CoinPaymentsTransaction


class CoinPaymentsTransactionDeleteView(DeleteView):
    model = CoinPaymentsTransaction


class CoinPaymentsTransactionDetailView(DetailView):
    model = CoinPaymentsTransaction


class CoinPaymentsTransactionUpdateView(UpdateView):
    model = CoinPaymentsTransaction


class CoinPaymentsTransactionListView(ListView):
    model = CoinPaymentsTransaction


class PaymentCreateView(CreateView):
    model = Payment


class PaymentDeleteView(DeleteView):
    model = Payment


class PaymentDetailView(DetailView):
    model = Payment


class PaymentUpdateView(UpdateView):
    model = Payment


class PaymentListView(ListView):
    model = Payment


# ipn_version = '1.0'
# ipn_id = 'ce041097ff2647f3c01375eacdc90e1d'
# ipn_mode = 'hmac'
# merchant = '8d683f17575a9544c6180206f52d4a9c'
# ipn_type = 'api'
# txn_id = 'CPCH5TRXAUDLO6ANAV2UCKDFN2'
# status = '0'
# status_text = 'Waiting for buyer funds...'
# currency1 = 'BCH'
# currency2 = 'BCH'
# amount1 = '1'
# amount2 = '1'
# fee = '0.006'
# buyer_name = 'CoinPayments API'
# invoice = '128fee28-2d37-448e-a339-71980a8950c1'
# received_amount = '0'
# received_confirms = '0'

# <QueryDict: {'amount1': ['1'], 'amount2': ['1'], 'buyer_name': ['CoinPayments API'], 'currency1': ['BCH'], 'currency2': ['BCH'], 'fee': ['0.006'], 'invoice': ['7b1af7d8-5e06-4fbb-8b27-64b0e89d2388'], 'ipn_id': ['545a488a9cb7f37b88e537367395c5d2'], 'ipn_mode': ['hmac'], 'ipn_type': ['api'], 'ipn_version': ['1.0'], 'merchant': ['8d683f17575a9544c6180206f52d4a9c'], 'received_amount': ['0'], 'received_confirms': ['0'], 'status': ['0'], 'status_text': ['Waiting for buyer funds...'], 'txn_id': ['CPCH7FVM3DLIBXFTORBRAMXVQY']}>
# HTTP_HMAC'9320f7f970294b0ea2c6e82519f839a65972c635bb137f3de859f5ede37c0adfa0607c10c8a3ce41dca3c038beab1b685013fb9fca8fdec984342e2338b5b6e0'
@csrf_exempt
def ipn_view(request):
    body = str(request.body)
    p = request.POST
    ipn_mode = p.get('ipn_mode')
    if ipn_mode != 'hmac':
        return HttpResponseBadRequest('IPN Mode is not HMAC')
    http_hmac = request.META.get('HTTP_HMAC')
    if not http_hmac:
        return HttpResponseBadRequest('No HMAC signature sent.')
    # set your secret in this function if you want your code works:)
    our_hmac = create_ipn_hmac(body)

    print("Our hmac == server hmac - {res}" % {'res': str(our_hmac == http_hmac)})
    if our_hmac != http_hmac:
        return HttpResponseBadRequest('Wrong HMAC signature provided.')

    merchant_id = getattr(settings, 'COINPAYMENTS_MERCHANT_ID', None)
    if p.get('merchant') != merchant_id:
        return HttpResponseBadRequest('Invalid merchant id')
    tx_id = p.get('txn_id')
    payment = Payment.objects.filter(provider_tx_id__exact=tx_id).first()
    if payment:
        if payment.currency_original != p.get('currency1'):
            return HttpResponseBadRequest('Currency mismatch')
        if payment.status != Payment.PAYMENT_STATUS_PAID:
            # Payments statuses: https://www.coinpayments.net/merchant-tools-ipn
            # Safe statuses: 2 and >= 100
            status = int(p['status'])
            if status == 2 or status >= 100:
                logger.info('Received payment for transaction {} - payment {} ({})'
                            .format(str(tx_id), str(payment.id), str(payment.amount)))
                payment.amount_paid = payment.amount
            else:
                payment.amount_paid = Decimal(p['received_amount'])
            if payment.amount_paid == payment.amount:
                payment.status = Payment.PAYMENT_STATUS_PAID
            payment.save()
# payment = Payment.objects.create(currency_original=tariff.currency, currency_paid=form_data['currency'],
#                                          status=PAYMENT_STATUS_PROVIDER_PENDING,
#                                          amount=tariff.cost, amount_paid=decimal.Decimal(0), order=order)
# return create_tx_and_redirect(payment, form_data['name'], service.pk)

# def create_tx_and_redirect(payment, name, number):
#     try:
#         tx = payment.create_tx(item_name=name, item_number=number)
#         payment.status = PAYMENT_STATUS_PENDING
#         payment.save()
#         return redirect(reverse('main:payment_detail', kwargs={'pk': payment.pk}))
#     except ProviderError as e:
#         # TODO redirect to error page with info about provider error
#         return ''
#
# def create_new_payment(request, pk):
#     payment = get_object_or_404(Payment, pk)
#     if payment.status in [PAYMENT_STATUS_PROVIDER_PENDING, PAYMENT_STATUS_TIMEOUT]:
#         pass
#     elif payment.status in [PAYMENT_STATUS_PENDING]:
#         payment.provider_tx.delete()
#     else:
#         # TODO: redirect to payment status mismatch error page
#         return ''
#     service = payment.order.get_service()
#     return create_tx_and_redirect(payment, service.name, service.pk)

example/example/views.py
from django import forms
from django_coinpayments.models import Payment
from django_coinpayments.exceptions import CoinPaymentsProviderError
from django.views.generic import FormView, ListView, DetailView
from django.shortcuts import render, get_object_or_404
from decimal import Decimal


class ExamplePaymentForm(forms.ModelForm):
    class Meta:
        model = Payment
        fields = ['amount', 'currency_original', 'currency_paid']


def create_tx(request, payment):
    context = {}
    try:
        tx = payment.create_tx()
        payment.status = Payment.PAYMENT_STATUS_PENDING
        payment.save()
        context['object'] = payment
    except CoinPaymentsProviderError as e:
        context['error'] = e
    return render(request, 'django_coinpayments/payment_result.html', context)


class PaymentDetail(DetailView):
    model = Payment
    template_name = 'django_coinpayments/payment_result.html'
    context_object_name = 'object'


class PaymentSetupView(FormView):
    template_name = 'django_coinpayments/payment_setup.html'
    form_class = ExamplePaymentForm

    def form_valid(self, form):
        cl = form.cleaned_data
        payment = Payment(currency_original=cl['currency_original'],
                          currency_paid=cl['currency_paid'],
                          amount=cl['amount'],
                          amount_paid=Decimal(0),
                          status=Payment.PAYMENT_STATUS_PROVIDER_PENDING)
        return create_tx(self.request, payment)


class PaymentList(ListView):
    model = Payment
    template_name = 'django_coinpayments/payment_list.html'


def create_new_payment(request, pk):
    payment = get_object_or_404(Payment, pk=pk)
    if payment.status in [Payment.PAYMENT_STATUS_PROVIDER_PENDING, Payment.PAYMENT_STATUS_TIMEOUT]:
        pass
    elif payment.status in [Payment.PAYMENT_STATUS_PENDING]:
        payment.provider_tx.delete()
    else:
        error = "Invalid status - {}".format(payment.get_status_display())
        return render(request, 'django_coinpayments/payment_result.html', {'error': error})
    return create_tx(request, payment)

example/templates/django_coinpayments/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block title %}django-coinpayments{% endblock title %}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="">
  <meta name="author" content="">

  <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
  <!--[if lt IE 9]>
  <script src="https://html5shim.googlecode.com/svn/trunk/html5.js"></script>
  <![endif]-->

  {% block css %}
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/css/bootstrap.css">

    <!-- Your stuff: Third-party css libraries go here -->

  {% endblock %}
</head>

<body>

<div class="m-b">
  <nav class="navbar navbar-dark navbar-static-top bg-inverse">
    <div class="container">
      <a class="navbar-brand" href="/">django-coinpayments</a>
      <button type="button" class="navbar-toggler hidden-sm-up pull-xs-right" data-toggle="collapse"
              data-target="#bs-navbar-collapse-1">
        &#9776;
      </button>

      <!-- Collect the nav links, forms, and other content for toggling -->
      <div class="collapse navbar-toggleable-xs" id="bs-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

<div class="container">

  {% if messages %}
    {% for message in messages %}
      <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
    {% endfor %}
  {% endif %}
  <div class="row" style="margin-bottom: 20px">

    <a class="btn btn-primary" href="/" style="margin-right: 20px">Home</a>
    <a class="btn btn-primary" href="{% url 'payment_list' %}">Payments list</a>
  </div>
  {% block content %}
    <div class="row m-t-2">
      <p>Use this document as a way to quick start any new project.</p>
      <p>The current template is loaded from
        <code>django-coinpayments/example/templates/base.html</code>. </p>
      <p>Whenever you overwrite the contents of <code>django-coinpayments/django_coinpayments/urls.py</code> with your
        own content, you should see it here.</p>
    </div>
  {% endblock content %}

</div> <!-- /container -->

{% block modal %}{% endblock modal %}

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
{% block javascript %}
  <!-- Latest JQuery -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.0/jquery.min.js"></script>

  <!-- Tether - a requirement for Bootstrap tooltips -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.2.0/js/tether.min.js"></script>

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://cdn.rawgit.com/twbs/bootstrap/v4-dev/dist/js/bootstrap.js"></script>

  <!-- Your stuff: Third-party javascript libraries go here -->

{% endblock javascript %}
</body>
</html>

example/templates/django_coinpayments/payment_list.html
{% extends 'django_coinpayments/base.html' %}
{% block content %}
  <ul>


    {% for obj in object_list %}
      <li>
        Payment #{{ obj.id }}, {{ obj.amount_paid.normalize }} {{ obj.get_currency_paid_display }}
        of {{ obj.amount.normalize }} {{ obj.get_currency_paid_display }} paid. <br>
        Status: {{ obj.get_status_display }}
        <br>
        <a class="btn btn-primary" href="{% url 'payment_new' obj.pk %}">Create a new transaction</a>
        <a class="btn btn-primary" href="{% url 'payment_detail' obj.pk %}">View transaction details</a>
      </li>
    {% endfor %}
  </ul>
{% endblock content %}

example/templates/django_coinpayments/payment_result.html
{% extends 'django_coinpayments/base.html' %}
{% block content %}
  {% if error %}
    <div class="alert alert-danger" role="alert">
      An error occured: {{ error }}
    </div>
  {% else %}
    Payment created successfully.
    Payment amount: {{ object.amount.normalize }} {{ object.get_currency_original_display }}
    <h4>CoinPayments.net Transaction <strong>{{ object.provider_tx.id }}</strong></h4>
    <p>
      Send {{ object.provider_tx.amount.normalize }}
      {{ object.get_currency_paid_display }}
      to {{ object.provider_tx.address }}
    </p>
    <p>Time left to pay:<br><span class="countdown"
                                  data-date="{{ object.provider_tx.timeout|date:"SHORT_DATE_FORMAT" }} {{ object.provider_tx.timeout|time:"H:i" }}"
                                  data-date-fallback="Timeout exceed"></span></p>
    <img src="{{ object.provider_tx.qrcode_url }}"><br>
    <a class="btn btn-primary" href="{{ object.provider_tx.status_url }}" target="_blank">
                <span class="btn__text">
                  View status
                </span>
    </a>
  {% endif %}
{% endblock content %}

example/templates/django_coinpayments/payment_setup.html
{% extends 'django_coinpayments/base.html' %}
{% block content %}

  <form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="btn btn-primary" type="submit">Submit</button>
  </form>

{% endblock content %}